### all
GET http://localhost:3000/grades HTTP/1.1
### get by id
GET http://localhost:3000/grades/2 HTTP/1.1
### add new student
POST http://localhost:3000/grades HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "id":3,
    "name": "New student", 
    "course" : "CS572",
    "grade": 98
}
###delete by id
DELETE http://localhost:3000/grades/3 HTTP/1.1
###put by id
PUT http://localhost:3000/grades HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "id":0,
    "name": "Name changed", 
    "course" : "CS572",
    "grade": 98
}